### DISCUSSION TITLE
Scheduling Kubernetes Workfloads across Nodes, Availability Regions and Zones

### DISCUSSION THREAD

**Discussion by JayGhiya** [unoplat/.github#32] [General]
# Stateful

## References

- https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
- https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#operators
- https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/
- https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
- https://stackoverflow.com/questions/73157345/kubernetes-spread-pods-across-nodes-using-podantiaffinity-vs-topologyspreadconst

**Comment by JayGhiya** [comment]
We could start with a default config:

```
apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
profiles:
  - schedulerName: default-scheduler
    pluginConfig:
      - name: PodTopologySpread
        args:
          defaultConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
          defaultingType: List

```
